# Generated by Django 4.1.7 on 2023-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_remove_person_cover_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mark_grad',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mark_hs',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
